################################################################################
# training parameters
################################################################################
train:
  lr: 0.005              # adam learning rate
  min_lr: 0.00001        # min(init) sgd lr  default:0.00001
  max_lr: 0.001            # max sgd learning rate     default:0.1
  wup_epochs: 1          # warmup during first XX epochs (can be float)
  max_epochs: 100
  momentum: 0.9          # sgd momentum
  lr_decay: 0.99         # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0001        # weight decay
  batch_size: 2          # batch size per gpu
  report_batch: 10       # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  epsilon_w: 0.001       # class weight w = 1 / (content + epsilon_w)
  workers: 6             # number of threads to get data
  flow: True
  lr_step: [50, 75, 90]
  lr_factor: 0.1
  optimizer: "sgd"       # adam or sgd
  syncbn: False

################################################################################
# loss parameters
################################################################################
loss:
  range_proj: 1.0
  polar_proj: 1.0
  range: 2.0
  polar: 2.0
  fusion: 2.0

################################################################################
# backbone parameters
################################################################################
backbone:
  name: "ResNet" 
  input_depth:
    range: True
    xyz: True
    remission: True
  dropout: 0.01
  bn_d: 0.01
  train: True # train backbone?
  layers: 34       # [34, 50]

################################################################################
# dataset parameters
dataset:
  labels: "rellis"
  scans: "rellis"
  max_points: 130000  # max of any scan in dataset
  drop: True
  drop_rate: 0.1
  scale: True
  scale_rate: 0.1
  sensor:
    name: "Ouster64"
    type: "spherical" # projective

################################################################################
# range view parameters
################################################################################
range:
  max_points: 130000 # max of any scan in dataset
  type: "spherical"  # projective
  proj: "v1"         # ['v1', 'v2']
  hres: True         # good
  flip: False        # bad
  trans: True        # good
  rot: False         # bad
  factor: [6, 3]     # for H, W separately
  sensor_img_H: 64
  sensor_img_W: 2048
  sensor_img_means:  #range,x,y,z,signal
    - 4.84649722
    - -0.187910314
    - 0.193718327
    - -0.246564824
    - 0.00260723157
  sensor_img_stds:   #range,x,y,z,signal
    - 6.05381850
    - 5.61048984
    - 5.27298844
    - 0.849105890
    - 0.00284712457
  sensor_fov_up: 22.5
  sensor_fov_down: -22.5

################################################################################
# polar view parameters
################################################################################
polar:
  rotate_aug: True
  flip_aug: True
  noise_aug: True
  fixed_volume_space: True
  grid_size: [480, 360, 32]
  return_test: False